MoCo-GHE-Admin/github-scripts

repo_archiver.py
The 422 error on closing issue/pull requests is difficult to diagnose, and I haven't found anyone experiencing it - so continue to capture and work around it.  Added a return from the issue closing that False's if there's a 422 error, and then adds a pause so you can close things manually and archive the repo before continuing on.
This is handy when doing MANY repos - archived ~250 recently - 3 had this problem, but without this pause, things would archive, I'd have to go manually reopen, deal with things, and rearchive.
=> Add a pause element to the archiver if the 422 error is detected.

gh_org_licenses.py, org_user_membership.py, repo_activity.py, utils.py
=> Working on converging to using utils.py for actual shared code

README.md, org_remove_user.py
In the eventual world where we know GHID's this script will be the way to remove users.
=> Initial commit of org_remove_user.py

README.md, repo_activity.py, requirements.txt, utils.py
Removing unneeded commit ananlysis (fixes #27)
Added analysis of wikis to change update date if needed (fixes #28)
Updated requirements and readme to reflect the above.
=> Updating repo_activity.py to better match reality

README.md, gh_api_remain.py, repo_activity.py, utils.py
Added the gh_api_remain script to display the amount of api rate remaining.  Also updated the utility module to display when the rate refreshes.
=> Repo activity fix

README.md, repo_archiver.py, repo_unarchiver.py
Setup the archiver to allow for a custom label to be applied to issues/pulls and inserted into the description.  This allows to add an explanatory URL (if shortened, as there's a 50 char limit to labels).  The unarchiver has been made agnostic to this, it detects the right things to remove.
=> Archiver labeler

repo_archiver.py, requirements.txt
Now prints out URL for ease of manual fixing of issues
Now archives for you unless "n" is hit after the pause.
=> improving handling of 422 errors in archiver

README.md, org_repos.py, repo_add_user.py, requirements.txt
mainly used for OC conversion work.
=> add user permissions to a repo

.pre-commit-config.yaml, org_user_membership.py, requirements.txt
Adding * to the repo name if the repo is archived.  Useful for auditing and removing users who only have defunct repos.
=> Membership archive

README.md, org_secret_alerts.py
for dumping secret alerts for entire org
Results outputted as csv data for ease of processing/importing to spreadsheets
=> Initial add of org_secret_alerts.py

README.md, gh_file_search.py
Updating `gh_file_search.py` to be more useful in finding code.
=> File search

org_samlreport.py
Old version worked until 100 users, due to not handling pagination correctly.  Updated to allow for the pagination to be properly processed.
=> Updated org_samlreport to work with pagination of results

README.md, gh_pat_owner.py
Script to grab details of a given Personal Access Token
=> Pat owner Script

org_samlreport.py, repo_active_users.py
Worked around case where SAML report is finding a SAML ID but no github ID.
=> Fixsamlreport

repo_unarchiver.py
Makes the unarchiver mention if it can't reopen PR's due to missing branches, and allows it to be run several times without error to step through the problems.
=> Making unarchiver more flexible/forgiving Closes #55

gh_file_search.py
The text match reporting was just adding a lot of noise to the search runs.  Removed it.
=> Making search a little more useful, removing the text match reporting

README.md, repo_close_issues.py
A script to close all issues in a repo.  Occasionally useful for cleanup efforts.  Can be given a closing comment.
=> Initial commit of repo_close_issues.py script

.pre-commit-config.yaml
with mac updates, python version changes, working on changes so we don't get beholden to that.
=> updating .pre-commit-config

README.md, org_audit_licensefile.py
Obeys rate limits, outputs spinner for activity sake, and has created date and and html URL in the output
=> Updates to audit_licensefile

.github/workflows/main.yml, gh_dependency_search.py, org_audit_licensefile.py, org_teams.py, repo_close_issues.py, tests/test_binaries_help_output.sh
Creating a new PR with #73's contents, but pushed to this repo so CI runs.
---
Changes:
- Forgot to run `pre-commit -av` in #54. Fixes those errors.
- Missed some imports of `util`. Fixes those.
- Adds a test that verifies that all executables can run `-h` and exit 0 to catch this in the future.
- Github Actions: Run pytest.
Make sure to run `pip install -r requirements.txt`.
=> fix import and ci issues

README.md, gh_user_perms.py
Per a user request - making the perms able to skip archived repos.
=> Adding no-archive flag to gh_user_perms.py to skip archived repos

poetry.lock, pyproject.toml
I thought alive-progress had released the stderr change, but they have not. 
Roll back to my fork.
=> fix alive-progress

gh_pat_owner.py
Updating gh_pat_owner.py to report if the fail was likely due to non-existent user/pat
=> Updating gh_pat_owner.py to handle some more errors

org_find_hooks.py, org_find_keys.py
the -ghsa- repos in some orgs have no hooks/keys - but instead of reporting a 0 length - they report NotFoundError ... handling that quietly.
=> Fixing handling of -ghsa- repos for find_hooks/keys

.pre-commit-config.yaml, poetry.lock, pyproject.toml
see https://github.com/sktime/sktime/issues/4162
=> fix pre-commit issue

README.md, repo_team_singleton_audit.py
Audits listed repos and reports if they have any permissions not given by teams, to help detect repos needing better management 
closes issue #98
=> repo_team_singleton_audit.py initial add

README.md, org_team_perms.py
Fixing column headers
Also updating org_teams_perms to be able to query just one team.
=> Fixing and updating org_teams_perms.py

repo_activity.py
Adding a space to ignore the wiki in the calculations.  Also including data on if the repo is a fork of other repos.  This is handy for calculations like "settings that change depending on when the original repo was created".
=> Updating activity script

README.md, org_add_user.py
Script to invite a user to an org, options for making them an owner, as well as optional team list.
=> Initial commit of 'org_add_user.py'

org_add_user.py
Listing the teams in the output when teams are specified.
=> org_add_user - cleaning up and adding to output
