repo_archiver.py
utils.py

I'm lazy and security focused, so I don't want to have to paste the key every run and I don't want to have to put it on the command line. 
Load it from the same file I use for my cis_tools scripts.
- Degrades gracefully if you don't have the file (still prompts if not passed in as an arg).

archiver: load gh token from a file

---

README.md
gh_org_licenses.py

This is a script to got through a list of orgs and give you a deduped number of licenses needed
Added a flag to allow for pending invites to count towards license count
This is what GHE does in their BI analysis
Added logic to handle not overrunning your rate limits.

gh_org_licenses.py - license count scripting

---

README.md
repo_archiver.py
repo_unarchiver.py

Adding "--inactive" flag to archiver.  Used to change the wording of the messages from
"abandoned" "deprecated" to "inactive" ... implying less draconian judgement.  Useful for
automated tasks that might overreach, and cause panic with their judegment.

Updating repo_archiver and unarchiver to handle "inactive" reasons for archiving.

---

README.md
repo_activity.py

ignore -ghsa- repos as they never have issues, and aren't really in use either.
if issues are examined, output the issue count.
if there are many issues, don't look at them all, set the activitydate to now, and add "-MANY-ISSUES" to the repo name.
added a spinner - if you're looking at 100 issues, there's no indication that it's DOING anything.

repo_activity.py - adjusted how it looks at issues for activity

---

org_samlreport.py

I was missing a scope on the PAT I was using, but it was hard to see what was wrong.
Catch the error and let user inspect the output for debugging.

catch KeyError exception and warn

---

repo_active_users.py

Script to get N days worth of active users (either by committer or author email field) from the actual git repos.

Initial add of repo_active_users.py

---

org_samlreport.py

My wrapper script for org_samlreport (in https://github.com/MoCo-GHE-Admin/cis_tools/pull/19) needs to know what org the output it receives is for. To avoid having to specify this, have org_samlreport add a comment header to the output with structured data (currently just the gh_org used and a timestamp).
new output:
```bash
SAML,GH Login
None,21echoes
```

org_samlreport: add comment header with structured data

---

README.md
gh_org_repo_perms.py

Default action is still dump the entire org, but will allow --user or --repo flag to limit
the result to just the user or repo.
Also, renamed from org_user_membership.py to  gh_org_repo_perms.py to reflect the change.

Modify org_user_membership to allow single user and repo queries

---

repo_close_issues.py

Added a >1 second pause between close requests, per https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits.

Avoiding rate limits and correcting language in close_issues

---

README.md
repo_close_issues.py

to better control avoiding secondary rate limits, increased default pause to 2 seconds and made it a parameter.

Add delay parameter to repo_close_issues

---

README.md
gh_file_search.py
org_audit_licensefile.py

File to enable auditing the repos in an org (or list of orgs) to find any that aren't licensed, or wrongly licensed.

License audit for LICENSE files in repos in an org

---

README.md
gh_api_remain.py
gh_dependency_search.py
gh_file_search.py
gh_org_licenses.py
gh_org_repo_perms.py
gh_user_moderation.py
gh_user_perms.py
github_scripts/utils.py
org_audit_licensefile.py
org_comms_team.py
org_owners.py
org_remove_user.py
org_repos.py
org_samlreport.py
org_secret_alerts.py
org_teams.py
repo_active_users.py
repo_activity.py
repo_add_perms.py
repo_archiver.py
repo_close_issues.py
repo_unarchiver.py

Created `utils.GH_ArgParser` with default token/patfile handling, and then revamped the scripts to use that instead of the scattershot "some do toml files, some do token, some do both, etc"

Setup a custom argparser with the usual suspects - and use it

---

github_scripts/utils.py
org_dependency_search.py

Make the rate-remain code handle progress bars rather than assume oldstyle spinner.

Add better handling between old-spinner and new-progress

---

README.md
issueconf.yaml.example
repo_issue_create.py

and example for the associated conf file
Script to open issues based on the issueconf.yaml.example file title: title of the issue
body: Body of the issue
bodyUID: some unique string for identification of the issue comment: comment for any already existing issue.
Has options to reopen issues if they're found closed, and add the comment to that or other issues
adding UID to the issues to allow for better identification of issues.

Initial add of repo_issue_create.py 

---

.github/workflows/main.yml

The workflows items in the actions have been giving deprecation notices for nodejs and some others for awhile.  Updating to get past the nodejs warnings.  (and appears to have cleared the other warnings as a side effect.)

Updating workflow to remove nodejs deprecation

---

README.md
github_scripts/utils.py
org_repo_perms.py
org_team_perms.py

New scripts for better reporting on permissions in an org/repo
They use the graphql api, which allows for better (more like the WebUI) reporting on permissions. org_team_perms reports on all teams, and the repos they're associated with with the pernmission level called out org_repo_perms reports on all repos, reporting every user that ISN'T getting their permissions from a team
The permission names are the same that the webUI uses, rather than "push/pull/admin" you have "read/write/maintain/triage/admin/<customnames"
Also updated the utils modules to have rate limit detecting code for the graphql.

Adding org_repo_perms and org_team_perms for better reporting

---

README.md
user_repo_query.py

Script to query a specific user for all permissions in given orgs.  (if no org reported, then all orgs the calling user has membership in).  Report can either be the default of one repo per line, or a more condensed one org per line.

User repo query Script

---

README.md
repo_activity.py

Since the activity script is commonly used to pick out aged targets for archiving - adding a filter date to ignore any entry with activity more recent than that.

Adding filter date to the repo_activity.py script

---

.pre-commit-config.yaml
README.md
gh_dependency_search.py
gh_file_search.py
gh_org_licenses.py
gh_user_moderation.py
org_audit_licensefile.py
org_owners.py

Orgini was envisioned as a quick way to give a list of orgs to the scripts. Over the years, it's just gone unused, and hasn't been added to most of the current scripts, and it's not missed.
org_owners.py
gh_dependency_search.py
org_audit_licensefile.py
gh_file_search.py
gh_org_licenses.py
gh_user_moderation.py
README.md
Have all had orgini removed, and the org list made required.

Removing orgini references as unused - closes #12

---

README.md
org_list.py
orglist.ini-EXAMPLE

This is useful for the cases where you want the list of all orgs so you can run OTHER scripts here against them.

Adding org_list.py to list all orgs the running user belongs to

---

org_audit_licensefile.py
org_dependency_search.py
org_repo_perms.py
poetry.lock

Not all scripts fail on bad pat - and several fail with a proper error message.  Adding exception handling to those that failed in non-obvious ways.  
org_audit_licensefile.py
org_dependency_search.py
org_repo_perms.py
This is usually a thing with the scripts that are poking the graphql endpoints.

Adding clarification for scripts that fail when PAT's aren't authorized

---

repo_archiver.py

The existing hook/key alerts in the archiver script are unclear about if the specific item is hook or key - adding "HOOK" or "KEY" allows a buik operation to happen and the hooks and keys be grepped out.

Adding HOOK/KEY to the output of hooks and keys to ease group archive operations.

---

README.md
github_scripts/utils.py
org_list.py
org_remove_user.py

Added code to help with guessing usernames based on email and fullname. Remade the collaborator search to use code like in mozilla/github-org-scripts/remove_member_from_org.py (Thanks Hal) - making the search org fast rather than looking at every repo.  This does make it invisible WHICH repo they had perms to - but that data can be collected in the UI Added links so that you can remove from IDP.
Added progress bars and verbose mode for more detail.

Improvements to org_remove_user.py

---

org_dependency_search.py

When detecting a repo that has too much to look through - print out a message so people can manually check, and proceed with the search.

Add too-many-deps error output to org_dependency_search

---

README.md
org_repo_perms_classic.py

to deal with the rest-api being nicer about non-documented API limits than graphql
Currently only reports on admin users, as that's the most common use case.

Remade org_repo_perms as org_repo_perms_classic 

---

README.md
enterprise_copilot_stats.py

Script to utilize the https://docs.github.com/en/enterprise-cloud@latest/rest/copilot/copilot-metrics?apiVersion=2022-11-28#get-copilot-metrics-for-an-enterprise APIs - which replaced the much simpler https://docs.github.com/en/enterprise-cloud@latest/rest/copilot/copilot-usage?apiVersion=2022-11-28 API
The old version could be easily queried for top level stats with a jq script - this one needs a little more structure.  Reports "Active Users" (there's an "Engaged user" as well, but with no indication as to the difference.) and the code suggestions and accepted suggestions per day.

Adding enterprise_copilot_stats.py to help track copilot usage

---

README.md
org_repo_perms_classic.py

Turns out _classic had some bugs - fixing them and making the ADMIN perms explicit in the output like in the non-_classic form

Updating and fixing org_repo_perms_classic.py
